Repository mindspore-ai/infrastructure, pull requests merged in 2020-03, with the labels that each got.

#13 Add repos mirror periodic job
  .github/workflows/repos-mirror.yml
Labels: approved, lgtm, size/S

#14 Remove the PR triggered event
  .github/workflows/repos-mirror.yml
Labels: approved, lgtm, size/XS

#16 update dockerfile of static_check and ubuntu-gpu
  development/jenkins/dockerfile/slaves/mindspore_check/Dockerfile
  development/jenkins/dockerfile/slaves/ubuntu-gpu/Dockerfile
  development/jenkins/dockerfile/slaves/ubuntu-gpu/requirements.txt
Labels: approved, lgtm, size/L

#17 Bump jenkins slave images
  production/jenkins-x86-slave/medium-slaves.yaml
  production/jenkins-x86-slave/small-slaves.yaml
Labels: approved, do-not-merge/hold, size/XS

#18 Add more memory for x86 jenkins slave
  production/jenkins-x86-slave/medium-slaves.yaml
  production/jenkins-x86-slave/small-slaves.yaml
Labels: approved, size/XS

#19 update dockerfile of aarch64_euleros
  development/jenkins/dockerfile/slaves/euleros-davinci/Dockerfile
  development/jenkins/dockerfile/slaves/euleros-davinci/requirements.txt
  development/jenkins/dockerfile/slaves/ubuntu-gpu/Dockerfile
Labels: approved, lgtm, size/L

#20 update version of arm-euleros image
  production/jenkins-arm-slave/medium-slaves.yaml
Labels: size/XS

#22 Disable the periodic mirror
  .github/workflows/repos-mirror.yml
Labels: size/S
